package com.xiaoming.closie.ui.editor

import android.app.DatePickerDialog
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.xiaoming.closie.data.ImageStore
import com.xiaoming.closie.data.model.*
import com.xiaoming.closie.data.repository.WardrobeRepository
import com.xiaoming.closie.ui.BackButton
import com.xiaoming.closie.ui.Rose
import com.xiaoming.closie.ui.Section
import java.time.LocalDate

@Composable fun EditorScreen(repo:WardrobeRepository,itemId:String?,initialStatus:String?,done:()->Unit){val context=LocalContext.current;val original=remember{itemId?.let{repo.getItem(it)}};var item by remember{mutableStateOf(original?:ClothingItem(status=if(initialStatus=="RETURNED")ItemStatus.RETURNED else ItemStatus.OWNED,purchaseDate=LocalDate.now().toString()))};var currentKind by remember{mutableStateOf(ImageKind.FLAT)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{ImageStore.copyFromUri(context,it)?.let{path->item=item.copy(images=item.images+ClothingImage(kind=currentKind,localPath=path))}}};@Composable fun text(label:String,value:String,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},modifier=Modifier.fillMaxWidth())};Scaffold(topBar={TopAppBar(title={Text(if(original==null)"添加衣服"else"编辑衣服")},navigationIcon={BackButton(done)})}){pad->LazyColumn(Modifier.padding(pad).padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{text("名称 *",item.name){item=item.copy(name=it)};text("类别",item.category){item=item.copy(category=it)};text("子类别",item.subcategory){item=item.copy(subcategory=it)}};item{SectionImages(item.images,{kind->currentKind=kind;picker.launch(arrayOf("image/*"))},{id->item=item.copy(images=item.images.filterNot{it.id==id})})};item{Text("购买信息",style=MaterialTheme.typography.titleMedium);text("品牌",item.brand){item=item.copy(brand=it)};text("购买店铺",item.store){item=item.copy(store=it)};text("购买平台",item.purchasePlatform){item=item.copy(purchasePlatform=it)};text("商品链接",item.productUrl){item=item.copy(productUrl=it)};text("购买价",item.price?.toString().orEmpty()){item=item.copy(price=it.toDoubleOrNull())};text("原价（可选）",item.originalPrice?.toString().orEmpty()){item=item.copy(originalPrice=it.toDoubleOrNull())};OutlinedButton(onClick={val d=runCatching{LocalDate.parse(item.purchaseDate)}.getOrDefault(LocalDate.now());DatePickerDialog(context,{_,y,m,day->item=item.copy(purchaseDate="%04d-%02d-%02d".format(y,m+1,day))},d.year,d.monthValue-1,d.dayOfMonth).show()}){Text("购买日期：${item.purchaseDate}")}};item{text("尺码标签",item.sizeLabel){item=item.copy(sizeLabel=it)};text("安全类别",item.safetyCategory){item=item.copy(safetyCategory=it)};text("我的评价",item.comment){item=item.copy(comment=it)};if(item.status==ItemStatus.RETURNED)text("退货原因",item.returnReason){item=item.copy(returnReason=it)}};item{DynamicMaterials(item.materials,{item=item.copy(materials=it)});DynamicMeasures(item.measurements,{item=item.copy(measurements=it)})};item{Button(enabled=item.name.isNotBlank(),onClick={if(original==null)repo.createItem(item)else repo.updateItem(item);done()},modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Rose)){Text("保存")}}}}}
@Composable private fun SectionImages(images:List<ClothingImage>,add:(ImageKind)->Unit,remove:(String)->Unit){Text("图片",style=MaterialTheme.typography.titleMedium);ImageKind.entries.forEach{kind->Row{Button(onClick={add(kind)}){Text("添加 ${kind.name}")};Text(" ${images.count{it.kind==kind}} 张");images.filter{it.kind==kind}.forEach{OutlinedButton(onClick={remove(it.id)}){Text("删除")}}}}}
@Composable private fun DynamicMaterials(values:List<MaterialPart>,set:(List<MaterialPart>)->Unit){Text("面料成分",style=MaterialTheme.typography.titleMedium);values.forEach{row->Row{OutlinedTextField(row.name,{v->set(values.map{if(it.id==row.id)it.copy(name=v)else it})},label={Text("成分")},modifier=Modifier.weight(1f));OutlinedTextField(row.percentage,{v->set(values.map{if(it.id==row.id)it.copy(percentage=v)else it})},label={Text("百分比")},modifier=Modifier.weight(1f));TextButton(onClick={set(values.filterNot{it.id==row.id})}){Text("删除")}}};OutlinedButton(onClick={set(values+MaterialPart())}){Text("+ 添加面料")}}
@Composable private fun DynamicMeasures(values:List<Measurement>,set:(List<Measurement>)->Unit){Text("具体尺寸",style=MaterialTheme.typography.titleMedium);values.forEach{row->Column{Row{OutlinedTextField(row.name,{v->set(values.map{if(it.id==row.id)it.copy(name=v)else it})},label={Text("尺寸名")},modifier=Modifier.weight(1f));OutlinedTextField(row.value,{v->set(values.map{if(it.id==row.id)it.copy(value=v)else it})},label={Text("数值")},modifier=Modifier.weight(1f));TextButton(onClick={set(values.filterNot{it.id==row.id})}){Text("删除")}}};OutlinedButton(onClick={set(values+Measurement())}){Text("+ 添加尺寸")}}
